[Log Starts]
2017-10-15 21:48:04,457 [WIPRO\RE246339] - Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: new1
Tracking Id:ddc6cacc627c4827adc92d1c637211d8-G:4-TimeStamp:10/15/2017 16:18:01
   at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SchedulerConsole.SendCloudToDevice.<SendCloudToDeviceMessageAsync>d__0.MoveNext() in f:\Back Up Remil\Remil\IOT\MS Accelerator\Dev\NewStick\SourceCod-Sched-Play-Stick Sep12\SourceCod-Sched-Play-Stick Sep12\SchedulerConsole2.6\SchedulerConsole2.6\SchedulerConsole\SendCloudToDevice.cs:line 49
2017-10-15 21:48:04,457 [WIPRO\RE246339] - Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: new1
Tracking Id:e5a29cd0a5804dc197e688cb38efe974-G:4-TimeStamp:10/15/2017 16:18:01
   at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SchedulerConsole.SendCloudToDevice.<SendCloudToDeviceMessageAsync>d__0.MoveNext() in f:\Back Up Remil\Remil\IOT\MS Accelerator\Dev\NewStick\SourceCod-Sched-Play-Stick Sep12\SourceCod-Sched-Play-Stick Sep12\SchedulerConsole2.6\SchedulerConsole2.6\SchedulerConsole\SendCloudToDevice.cs:line 49
2017-10-15 21:48:04,457 [WIPRO\RE246339] - Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: new1
Tracking Id:f2849ffaa9be4aecb800d9eb877453c4-G:4-TimeStamp:10/15/2017 16:18:01
   at Microsoft.Azure.Devices.AmqpServiceClient.<SendAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SchedulerConsole.SendCloudToDevice.<SendCloudToDeviceMessageAsync>d__0.MoveNext() in f:\Back Up Remil\Remil\IOT\MS Accelerator\Dev\NewStick\SourceCod-Sched-Play-Stick Sep12\SourceCod-Sched-Play-Stick Sep12\SchedulerConsole2.6\SchedulerConsole2.6\SchedulerConsole\SendCloudToDevice.cs:line 49
